### ISSUE TITLE
Next stop when following buses

### ISSUE THREAD

**Issue by fransgandersson** [will258012/CitiesSkylines-FPSCamera-Continued#3]
## Feature Description
Thanks for taking care of this mod. I think that a great addition, when following buses and other public-transport vehicles, would be to add "Next stop" (with the station name) in the info display, maybe under "Passenger".
Edit: "Next station" -> "Next stop".

## Proposed Solutions
Please see uploaded image

## Illustrations

<img width="1915" alt="suggestion" src="https://github.com/will258012/CitiesSkylines-FPSCamera-Continued/assets/6750162/88d9f960-23b6-4940-8148-799a8db79f25">

**Comment by will258012** [comment]
Hello! A new testing version is available on [Github](https://github.com/will258012/CitiesSkylines-FPSCamera-Continued/releases/tag/v2.4.0-b2) and [Steam Workshop](https://steamcommunity.com/sharedfiles/filedetails/?id=3281544449).
Please download and try the new version. Thanks for your suggestion!

**Comment by fransgandersson** [comment]
Awesome. thanks! 

A minor thing (which is my mistake because I suggested "station" in the first place): "Next stop" would be more idiomatic, just in case you fancy updating it at some point.
